# Generated by Django 2.0.13 on 2019-07-12 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0007_slugfield_noop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='line',
            options={'ordering': ['date_created', 'pk'], 'verbose_name': 'Basket line', 'verbose_name_plural': '購入履歴'},
        ),
        migrations.AlterModelTable(
            name='line',
            table='購入履歴',
        ),
    ]
    
    atomic = False
