# Generated by Django 2.0.13 on 2019-07-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_auto_20190712_1434'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='line',
            table=None,
        ),
    ]
    
    atomic = False
